package com.lado.travago.tripbook.model.admin

import com.google.android.libraries.places.api.model.Place
import com.google.firebase.Timestamp
import com.lado.travago.tripbook.model.enums.SEX
import java.util.*

/**
 * @author Tom Parkert
 * A Scanner is any person who has the ability to scan and confirm a
 * travellers ticket. He/She is affiliated to an [OnlineTravelAgency] and i located
 * at a particular [park] which is from the OnlineTransportAgency [Place] list. The id is automatically created in
 * by firestore
 *
 * @property uid is the id generated by firestore
 * @property name is the name of the scanner
 * @property birthdayInMillis is the birth day of the scanner expressed in milliseconds which will be used to calculate his age
 * @property sex is the gender of the scanner gotten from the [SEX] enum
 * @property profilePhoto is the url of the scanner's face photo
 * @property phoneNumber is the contact of the scanner used to LogIn & SignIn e.g MTN, ORANGE, NEXTELL
 * @property nationality is the birth country of the scanner
 * @property otaName is the [OnlineTravelAgency] which has employ that scanner to scan their customers ticket
 * @property park is the location of that scanner which must be part of that OnlineTransportAgency destination.
 * @property birthPlace is the location where this scanner was born
 * @property isAdmin this property if true means this scanner can create other scanners

 */
data class Scanner(
    var uid: String,
    var name: String,
    var birthdayInMillis: Long,
    var sex: SEX = SEX.UNKNOWN,
    var profilePhoto: String,
    var phoneNumber: String,
    var otaName: String,
    var park: Place? = null,
    var birthPlace: String,
    val nationality: String = "Cameroon",
    val isAdmin: Boolean = false,
) {
    var isActive: Boolean = false
    var numberOfScans: Int = 0

    /**
     * Generate a valid scanner hashMap for firestore
     */
    val scannerMap: HashMap<String, Any?> = hashMapOf(
        "uid" to uid,
        "name" to name,
        "phone" to phoneNumber,
        "sex" to sex,
        "birthday" to birthdayInMillis,
        "birthplace" to birthPlace,
        "Online Travel Agency" to otaName,
        "nationality" to "Cameroon",
        "park" to park,
        "isAdmin" to isAdmin,
        "isActive" to isActive,
        "numberOfScans" to numberOfScans,
        "photoUrl" to profilePhoto,
        "addedOn" to Timestamp(Date())
    )

    /**
     * An inner class which contains some basic information about the scanner.
     */
   data class ScannerBasicInfo(
        val name: String,
        val birthdayInMillis: Long,
        val isAdmin: Boolean,
        val phoneNumber: String,
        val photoUrl: String
    )


}
