package com.lado.travago.tripbook.model.users

import com.google.firebase.Timestamp
import com.lado.travago.tripbook.model.enums.OCCUPATION
import com.lado.travago.tripbook.model.enums.SEX
import java.util.*

/**
 *  * A Scanner is any person who has the ability to scan and confirm a
 * travellers ticket. He/She is affiliated to an [OnlineTravelAgency]. The id is automatically created by firestore
 *  This Scanner is a type of User, thus implements the [User] interface
 * @author Tom Parkert

 * @property bookerId is the id generated by firestore
 * @property name is the name of the scanner
 * @property birthdayInMillis is the birth day of the scanner expressed in milliseconds which will be used to calculate his age
 * @property sex is the gender of the scanner gotten from the [SEX] enum
 * @property photoUrl is the url of the scanner's face photo
 * @property recoveryPhoneNumber is the contact of the scanner used to LogIn & SignIn e.g MTN, ORANGE, NEXTELL
 * @property nationality is the birth country of the scanner
 * @property otaName is the [OnlineTravelAgency] which has employ that scanner to scan their customers ticket
 * @property birthPlace is the location where this scanner was born
 * @property isAdmin this property if true means this scanner can create other scanners

 */
data class Scanner(
    override var bookerId: String,
    override var name: String,
    override var birthdayInMillis: Long,
    override var sex: SEX = SEX.UNKNOWN,
    override var photoUrl: String,
    override var recoveryPhoneNumber: String,
    override val nationality: String = "Cameroon",
    override val occupation: OCCUPATION = OCCUPATION.SCANNER,
    var otaName: String,
    var isAdmin: Boolean,
    override var birthPlace: String,
): User {
    var isActive: Boolean = false
    var numberOfScans: Int = 0


    /**
     * An inner class which contains some basic information about the scanner.
     * It inherits from the [User.UserBasicInfo]
     * This class is used to display scanner info on a recyclerView
     */
    data class ScannerBasicInfo(
        override val name: String ,
        override val birthdayInMillis: Long,
        override val phoneNumber: String,
        override val photoUrl: String,
        override val occupation: OCCUPATION,
        val isAdmin: Boolean,
    ): User.UserBasicInfo(
        name,
        birthdayInMillis,
        phoneNumber,
        photoUrl,
        occupation
    )

    override val userMap: HashMap<String, Any?> = hashMapOf(
        "uid" to bookerId,
        "name" to name,
        "sex" to sex,
        "email" to recoveryPhoneNumber,
        "birthday" to birthdayInMillis,
        "birthplace" to birthPlace,
        "Online Travel Agency" to otaName,
        "nationality" to "Cameroon",
        "isAdmin" to isAdmin,
        "isActive" to isActive,
        "numberOfScans" to numberOfScans,
        "photoUrl" to photoUrl,
        "addedOn" to Timestamp(Date())
    )
}
